name: Changelog

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate markdown
        run: |
          cd changelog && npm ci && node generate-changelog.js && sh sort-changelog-versions.sh 
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --template=./changelog/template.html5 
            -V linkcolor:blue 
            -V fontsize=12pt 
            -f markdown_github
            -t html5
            ./changelog/README.md 
            -o index.html 
      - name: update file and push to remote
        run: |
          /bin/bash scripts/update-repo.sh
